apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: your-dockerhub/graphql-gateway:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: graphql-config
            - secretRef:
                name: graphql-secret
