apiVersion: v1
kind: Pod
metadata:
  name: kafka
spec:
  containers:
    - name: kafka
      image: wurstmeister/kafka
      env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
      ports:
        - containerPort: 9092
